### ISSUE TITLE
Missing 'Flask-Environments' dependency

### ISSUE THREAD

**Issue by arcimboldo** [uzh/msregistry#1]
When running:

  python manage.py db init

for the first time after running `pip install -r requirements/common.txt` I get the following error:

  Traceback (most recent call last):
    File "manage.py", line 27, in <module>
      from app import create_app, db
    File "/tmp/msregistry/app/**init**.py", line 29, in <module>
      from flask_environments import Environments
  ImportError: No module named flask_environments

After installing `Flask-Environments` package with `pip`, the `python manage.py db init` command succeeds.

**Comment by riccardomurri** [comment]
@filippopanessa maybe you should generate the `requirements.txt` file with `pip freeze` ?

**Comment by panessa** [comment]
I also forgot Flask-SSLify and MySQL-python. Corrected.

**Comment by arcimboldo** [comment]
I'm not sure mysql-python should be a dependency: since it uses sqlalchemy it can works with either sqlite backend (no extra dependency needed), or postgresql (which is not a dependency). I think it would be better to just mention in the README that _if_ you want to use an sql backend different from sqlite you should install the proper python module.

**Comment by panessa** [comment]
On 08. 02. 16 23:30, Antonio Messina wrote:

> I'm not sure mysql-python should be a dependency: since it uses
> sqlalchemy it can works with either sqlite backend (no extra dependency
> needed), or postgresql (which is not a dependency). I think it would be
> better to just mention in the README that /if/ you want to use an sql
> backend different from sqlite you should install the proper python module.

I think you're totally right. But I created requirements/prod.txt for
S3IT production purpose and I guess it should be better to move all this
kind of stuff there (like gunicorn that we use in conjunction with
supervisor and nginx).
